const GROQ_API_KEY = import.meta.env.VITE_GROQ_API_KEY;
const GROQ_API_URL = 'https://api.groq.com/openai/v1/chat/completions';

export const generateExamQuestions = async (topic, numQuestions = 5) => {
  try {
    if (!GROQ_API_KEY) {
      console.error('Groq API key is not set');
      throw new Error('Groq API key is not configured. Please check your environment variables.');
    }

    const prompt = `Generate exactly ${numQuestions} exam questions about the topic "${topic}" in a valid JSON object containing a "questions" key. 
    The "questions" key must map to an array of questions.
    
    Supported question types: "mcq" and "answerable".
    
    1. For MCQ ("type": "mcq") questions:
       - Must include 4 options: "optionA", "optionB", "optionC", "optionD".
       - Must specify the "correct_answer" as one of: "A", "B", "C", "D".
       - Example MCQ structure:
         {
           "question": "What is the capital of France?",
           "type": "mcq",
           "optionA": "London",
           "optionB": "Paris",
           "optionC": "Berlin",
           "optionD": "Madrid",
           "correct_answer": "B"
         }
         
    2. For Answerable ("type": "answerable") questions:
       - Must provide a detailed text solution in the "correct_answer" field.
       - Example Answerable structure:
         {
           "question": "Explain the concept of React hooks",
           "type": "answerable",
           "correct_answer": "React Hooks are functions that let you use state and other React features without writing classes."
         }
         
    Your output MUST be a JSON object conforming exactly to this schema:
    {
      "questions": [
         // list of ${numQuestions} questions here
      ]
    }`;

    console.log('Sending request to Groq API...');
    const requestBody = {
      model: "llama-3.3-70b-versatile",
      messages: [
        {
          role: "system",
          content: "You are a helpful exam creator assistant. You must output a JSON object containing a list of questions conforming exactly to the requested schema."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      response_format: { type: "json_object" },
      temperature: 0.7
    };

    const response = await fetch(GROQ_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${GROQ_API_KEY}`
      },
      body: JSON.stringify(requestBody)
    });

    const responseData = await response.json();
    console.log('Groq API Response:', responseData);

    if (!response.ok) {
      const errorMessage = responseData.error?.message || `HTTP error! status: ${response.status}`;
      console.error('Groq API Error:', errorMessage);
      throw new Error(`Groq API Error: ${errorMessage}`);
    }

    const contentText = responseData.choices?.[0]?.message?.content;
    if (!contentText) {
      console.error('No choices or content returned from Groq');
      throw new Error('No content was generated by Groq. Please try again.');
    }

    try {
      const parsedData = JSON.parse(contentText);
      if (!parsedData || !Array.isArray(parsedData.questions)) {
        throw new Error('Invalid response structure: expected an object with a "questions" array.');
      }
      console.log('Parsed questions from Groq:', parsedData.questions);
      return parsedData.questions;
    } catch (parseError) {
      console.error('Error parsing JSON from Groq:', parseError, contentText);
      throw new Error('Failed to parse the generated questions from Groq. Please try again.');
    }
  } catch (error) {
    console.error('Error in generateExamQuestions (Groq):', error);
    throw error;
  }
};
